FROM golang:1.24-bookworm AS build

WORKDIR /src
COPY adapters/OpenViking/broker_sidecar/go.mod adapters/OpenViking/broker_sidecar/go.sum ./
RUN go mod download
COPY adapters/OpenViking/broker_sidecar/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -trimpath -ldflags="-s -w" -o /out/openviking-broker-sidecar ./cmd/broker-sidecar

FROM scratch
LABEL org.opencontainers.image.title="Argus OpenViking SPIFFE Broker Sidecar"
LABEL argus.component="openviking-broker"
USER 1000:1000
COPY --from=build /out/openviking-broker-sidecar /openviking-broker-sidecar
ENTRYPOINT ["/openviking-broker-sidecar"]
