agent_address = "unix://@AGENT_SOCKET@"
daemon_mode = true
cert_dir = "@CREDENTIALS@"
broker {
    workload_id = "@WORKLOAD_ID@"
    endpoint = "unix://@BROKER_SOCKET@"
    helper_spiffe_id = "@HELPER_ID@"
    agent_spiffe_id = "@AGENT_ID@"
    target_spiffe_id = "@TARGET_ID@"
    target_registration_path = "@TARGET@"
    publish_hook = "@BIN@/nginx-hook.sh"
    startup_timeout = "@STARTUP_TIMEOUT@"
}
