#!/usr/bin/env bash
set -euo pipefail
# Generated from the approved deployment configuration; do not edit this file.
exec python3 @INSTALL@/scripts/nginx-hook.py --config @ETC@/environment.json "${1:?action required}"
